roboptim::eigen::SolverWithJacobian Class Reference
roboptim::eigen::SolverWithJacobian Class Reference
Solver implementing a variant of Levenberg-Marquardt algorithm.
#include <roboptim/core/plugin/eigen/eigen-levenberg-marquardt.hh>
Public Types
typedef Solver< SumOfC1Squares, boost::mpl::vector<> > parent_t
Parent type.
typedef problem_t::function_t function_t
Cost function type.
typedef parent_t::result_t result_t
type of result
typedef DifferentiableFunction::gradient_t gradient_t
type of gradient
typedef Function::size_type size_type
Size type.
typedef SolverState< parent_t::problem_t > solverState_t
Solver state.
typedef parent_t::callback_t callback_t
RobOptim callback.
Public Member Functions
SolverWithJacobian (const problem_t &problem)
Constructot by problem.
virtual ~SolverWithJacobian ()
virtual void solve ()
Solve the optimization problem.
size_type n () const
Return the number of variables.
size_type m () const
Return the number of functions.
Function::argument_t & parameter ()
Get the optimization parameters.
const Function::argument_t & parameter () const
Get the optimization parameters.
boost::shared_ptr< const DifferentiableFunction > cost () const
Get the cost function.
virtual void setIterationCallback (callback_t callback)
Set the callback called at each iteration.
const callback_t & callback () const
Get the callback called at each iteration.
Detailed Description
Solver implementing a variant of Levenberg-Marquardt algorithm.
This solver tries to minimize the euclidean norm of a vector valued function.
Member Typedef Documentation
typedef parent_t::callback_t roboptim::eigen::SolverWithJacobian::callback_t
RobOptim callback.
typedef problem_t::function_t roboptim::eigen::SolverWithJacobian::function_t
Cost function type.
typedef DifferentiableFunction::gradient_t roboptim::eigen::SolverWithJacobian::gradient_t
type of gradient
typedef Solver<SumOfC1Squares, boost::mpl::vector<> > roboptim::eigen::SolverWithJacobian::parent_t
Parent type.
typedef parent_t::result_t roboptim::eigen::SolverWithJacobian::result_t
type of result
typedef Function::size_type roboptim::eigen::SolverWithJacobian::size_type
Size type.
typedef SolverState<parent_t::problem_t> roboptim::eigen::SolverWithJacobian::solverState_t
Solver state.
Constructor & Destructor Documentation
roboptim::eigen::SolverWithJacobian::SolverWithJacobian (const problem_t & problem) explicit
Constructot by problem.
Referenced by create().
roboptim::eigen::SolverWithJacobian::~SolverWithJacobian () virtual
Member Function Documentation
const callback_t& roboptim::eigen::SolverWithJacobian::callback () const inline
Get the callback called at each iteration.
Referenced by setIterationCallback().
boost::shared_ptr<const DifferentiableFunction> roboptim::eigen::SolverWithJacobian::cost () const inline
Get the cost function.
size_type roboptim::eigen::SolverWithJacobian::m () const inline
Return the number of functions.
size_type roboptim::eigen::SolverWithJacobian::n () const inline
Return the number of variables.
Function::argument_t& roboptim::eigen::SolverWithJacobian::parameter () inline
Get the optimization parameters.
const Function::argument_t& roboptim::eigen::SolverWithJacobian::parameter () const inline
Get the optimization parameters.
virtual void roboptim::eigen::SolverWithJacobian::setIterationCallback (callback_t callback) inline virtual
Set the callback called at each iteration.
References callback().
void roboptim::eigen::SolverWithJacobian::solve () virtual
Solve the optimization problem.
References LOAD_RESULT_WARNINGS.