sudo: required
language: cpp
env:
  global:
  - APT_DEPENDENCIES="cmake cmake-data doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev"
  - HOMEBREW_DEPENDENCIES="doxygen log4cxx"
  - GIT_DEPENDENCIES="roboptim/roboptim-core"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - LCOV_IGNORE_RULES="*tests*"
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-core-plugin-eigen
  - secure: YurfcUtraOayjgYuay0IDyY2FssU53q91VzeYXzAd1VdxH9IAatXXwQpBj8i/dSPM/1NtpB3gISpBktOy+KN7to7gKWeOQHWQOPae0SbuTPfOE5uyl1zWTtOypA3CI51el1+kmYN39Qi4ASt9LN5CD1ZZrsso7aH2bS/6YLWchA=
  - secure: LRvqill/xVFcjMoco3qp0XrfGOi6U+syq1XbT7OTwZfHtIJii63McrmlqWP9d7vrxzwsi+F5i5fvpjLy6Idp7aX4myGiRXp7yZJC/rNVDVNbgosv4NNXE511S1C9ObGSksuTbF8oYa4qA8sMB1ZJW1A2cqeODBHYBr7rrEIIZ+U=
  - secure: XFVC3kdigudQBqS56o8aUGRimJZe4fYz8pNzwBjkqyLp7GFshzcWJqitR8lS+/pbg7PmrVsyEivFvSY9j0bd4XEvZQY+WOfJHfS6X9G0IEoXmKw52muNIt/AwRXeeD8dX5FqPbtO65vKP+zgItSrlCiWpTpTF0uDjRGW3SYyaZA=
notifications:
  hipchat:
    rooms:
      secure: LJbgx2sjAmTUu+AV8N/PSQHFQ8E1OnHAB2oYFv1XwN2hujtswNwE9k16etaEBRZ0IP1z7mTWrabaztDPC5efEaGpi4TZLMr5P9n/ABWRvJi+tVMXG7fusxTNzOaqcr31g2VQBXJ2nMZWxawP4xzTp+sSVcVsHm5xt4UjLyVQ6+A=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - dev
  - travis
  - debian
script:
  - export LD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$LD_LIBRARY_PATH;
  - if [ "${ENABLE_CXX11}" == "1" ]; then export CMAKE_ADDITIONAL_OPTIONS="-DUSE_CXX11:BOOL=ON -DROBOPTIM_PRECOMPILE_DENSE_SPARSE:BOOL=ON ${CMAKE_ADDITIONAL_OPTIONS}"; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then ./.travis/run build; fi
after_success:
  - ./.travis/run after_success
  - codecov --gcov-root=/tmp/_ci/build
after_failure: ./.travis/run after_failure
before_install:
  - pip install --user codecov
  - ./.travis/dependencies/eigen-3.2
  - ./.travis/run before_install
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CC=gcc CXX=g++ ./.travis/dependencies/ipopt; fi

matrix:
  allow_failures:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - env: COVERITY_SCAN_BRANCH=1
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
      env: ENABLE_CXX11=1
    - os: linux
      dist: precise
      compiler: gcc
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: linux
      dist: precise
      compiler: clang
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  coverity_scan:
    project:
      name: "roboptim/roboptim-core-plugin-eigen"
      description: "Build submitted via Travis CI"
    notification_email: roboptim@googlegroups.com
    build_command_prepend: ". .travis/common.sh && mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
